Update backend interface settings documentation
Sitefinity/sitefinity-admin-app-extensions pull request #468
Opened 2022-10-07 12:25 UTC by annix8

2022-10-07 12:36 UTC, Novkirishki commented on README.md
> +### Modifications done in the Backend interface settings
Shouldn't we remove this section's content and just add a link to the SF docs?

2022-10-07 12:37 UTC, Novkirishki commented on README.md
> +### Modifications done in the Backend interface settings
Same for all child READMEs. I expect that this is all moved to SF docs and is not needed here.

2022-10-07 12:37 UTC, Novkirishki requested changes
added as a single comment

2022-10-17 13:07 UTC, Novkirishki approved these changes

2022-10-19 07:40 UTC, KirilVandov approved these changes

2022-10-19 08:15 UTC, merged